
url: http://www.tiny-puppet.com
title: Example42
email: info@example42.com
author: Example42
description: > # "Tiny Puppet is an abstraction layer on top of Puppet DSL which allows installation and configuration of any application"

highlighter: pygments
markdown: kramdown
exclude: ['vendor']

